 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Header file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: AHMED KHALED
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

const Port_ConfigType Port_Configuration = {
                /*****************************************************************   PORT A  *************************************************************************/
		PORTA_ID,PIN0_ID,PORTA_PIN0_DIRECTION,PORTA_PIN0_DATA,PORTA_PIN0_MODE_TYPE,PORTA_PIN0_RESISTOR,PORTA_PIN0_DIRECTION_CHANGABLE,PORTA_PIN0_MODE_CHANGABLE, /* PIN0 */
		PORTA_ID,PIN1_ID,PORTA_PIN1_DIRECTION,PORTA_PIN1_DATA,PORTA_PIN1_MODE_TYPE,PORTA_PIN1_RESISTOR,PORTA_PIN1_DIRECTION_CHANGABLE,PORTA_PIN1_MODE_CHANGABLE, /* PIN1 */
		PORTA_ID,PIN2_ID,PORTA_PIN2_DIRECTION,PORTA_PIN2_DATA,PORTA_PIN2_MODE_TYPE,PORTA_PIN2_RESISTOR,PORTA_PIN2_DIRECTION_CHANGABLE,PORTA_PIN2_MODE_CHANGABLE, /* PIN2 */
		PORTA_ID,PIN3_ID,PORTA_PIN3_DIRECTION,PORTA_PIN3_DATA,PORTA_PIN3_MODE_TYPE,PORTA_PIN3_RESISTOR,PORTA_PIN3_DIRECTION_CHANGABLE,PORTA_PIN3_MODE_CHANGABLE, /* PIN3 */
		PORTA_ID,PIN4_ID,PORTA_PIN4_DIRECTION,PORTA_PIN4_DATA,PORTA_PIN4_MODE_TYPE,PORTA_PIN4_RESISTOR,PORTA_PIN4_DIRECTION_CHANGABLE,PORTA_PIN4_MODE_CHANGABLE, /* PIN4 */
		PORTA_ID,PIN5_ID,PORTA_PIN5_DIRECTION,PORTA_PIN5_DATA,PORTA_PIN5_MODE_TYPE,PORTA_PIN5_RESISTOR,PORTA_PIN5_DIRECTION_CHANGABLE,PORTA_PIN5_MODE_CHANGABLE, /* PIN5 */
		PORTA_ID,PIN6_ID,PORTA_PIN6_DIRECTION,PORTA_PIN6_DATA,PORTA_PIN6_MODE_TYPE,PORTA_PIN6_RESISTOR,PORTA_PIN6_DIRECTION_CHANGABLE,PORTA_PIN6_MODE_CHANGABLE, /* PIN6 */
		PORTA_ID,PIN7_ID,PORTA_PIN7_DIRECTION,PORTA_PIN7_DATA,PORTA_PIN7_MODE_TYPE,PORTA_PIN7_RESISTOR,PORTA_PIN7_DIRECTION_CHANGABLE,PORTA_PIN7_MODE_CHANGABLE, /* PIN7 */
                /*****************************************************************   PORT B  *************************************************************************/
		PORTB_ID,PIN0_ID,PORTB_PIN0_DIRECTION,PORTB_PIN0_DATA,PORTB_PIN0_MODE_TYPE,PORTB_PIN0_RESISTOR,PORTB_PIN0_DIRECTION_CHANGABLE,PORTB_PIN0_MODE_CHANGABLE, /* PIN0 */
		PORTB_ID,PIN1_ID,PORTB_PIN1_DIRECTION,PORTB_PIN1_DATA,PORTB_PIN1_MODE_TYPE,PORTB_PIN1_RESISTOR,PORTB_PIN1_DIRECTION_CHANGABLE,PORTB_PIN1_MODE_CHANGABLE, /* PIN1 */
		PORTB_ID,PIN2_ID,PORTB_PIN2_DIRECTION,PORTB_PIN2_DATA,PORTB_PIN2_MODE_TYPE,PORTB_PIN2_RESISTOR,PORTB_PIN2_DIRECTION_CHANGABLE,PORTB_PIN2_MODE_CHANGABLE, /* PIN2 */
		PORTB_ID,PIN3_ID,PORTB_PIN3_DIRECTION,PORTB_PIN3_DATA,PORTB_PIN3_MODE_TYPE,PORTB_PIN3_RESISTOR,PORTB_PIN3_DIRECTION_CHANGABLE,PORTB_PIN3_MODE_CHANGABLE, /* PIN3 */
		PORTB_ID,PIN4_ID,PORTB_PIN4_DIRECTION,PORTB_PIN4_DATA,PORTB_PIN4_MODE_TYPE,PORTB_PIN4_RESISTOR,PORTB_PIN4_DIRECTION_CHANGABLE,PORTB_PIN4_MODE_CHANGABLE, /* PIN4 */
		PORTB_ID,PIN5_ID,PORTB_PIN5_DIRECTION,PORTB_PIN5_DATA,PORTB_PIN5_MODE_TYPE,PORTB_PIN5_RESISTOR,PORTB_PIN5_DIRECTION_CHANGABLE,PORTB_PIN5_MODE_CHANGABLE, /* PIN5 */
		PORTB_ID,PIN6_ID,PORTB_PIN6_DIRECTION,PORTB_PIN6_DATA,PORTB_PIN6_MODE_TYPE,PORTB_PIN6_RESISTOR,PORTB_PIN6_DIRECTION_CHANGABLE,PORTB_PIN6_MODE_CHANGABLE, /* PIN6 */
		PORTB_ID,PIN7_ID,PORTB_PIN7_DIRECTION,PORTB_PIN7_DATA,PORTB_PIN7_MODE_TYPE,PORTB_PIN7_RESISTOR,PORTB_PIN7_DIRECTION_CHANGABLE,PORTB_PIN7_MODE_CHANGABLE, /* PIN7 */
                /*****************************************************************   PORT C  *************************************************************************/
		PORTC_ID,PIN0_ID,PORTC_PIN0_DIRECTION,PORTC_PIN0_DATA,PORTC_PIN0_MODE_TYPE,PORTC_PIN0_RESISTOR,PORTC_PIN0_DIRECTION_CHANGABLE,PORTC_PIN0_MODE_CHANGABLE, /* PIN0 */
		PORTC_ID,PIN1_ID,PORTC_PIN1_DIRECTION,PORTC_PIN1_DATA,PORTC_PIN1_MODE_TYPE,PORTC_PIN1_RESISTOR,PORTC_PIN1_DIRECTION_CHANGABLE,PORTC_PIN1_MODE_CHANGABLE, /* PIN1 */
		PORTC_ID,PIN2_ID,PORTC_PIN2_DIRECTION,PORTC_PIN2_DATA,PORTC_PIN2_MODE_TYPE,PORTC_PIN2_RESISTOR,PORTC_PIN2_DIRECTION_CHANGABLE,PORTC_PIN2_MODE_CHANGABLE, /* PIN2 */
		PORTC_ID,PIN3_ID,PORTC_PIN3_DIRECTION,PORTC_PIN3_DATA,PORTC_PIN3_MODE_TYPE,PORTC_PIN3_RESISTOR,PORTC_PIN3_DIRECTION_CHANGABLE,PORTC_PIN3_MODE_CHANGABLE, /* PIN3 */
		PORTC_ID,PIN4_ID,PORTC_PIN4_DIRECTION,PORTC_PIN4_DATA,PORTC_PIN4_MODE_TYPE,PORTC_PIN4_RESISTOR,PORTC_PIN4_DIRECTION_CHANGABLE,PORTC_PIN4_MODE_CHANGABLE, /* PIN4 */
		PORTC_ID,PIN5_ID,PORTC_PIN5_DIRECTION,PORTC_PIN5_DATA,PORTC_PIN5_MODE_TYPE,PORTC_PIN5_RESISTOR,PORTC_PIN5_DIRECTION_CHANGABLE,PORTC_PIN5_MODE_CHANGABLE, /* PIN5 */
		PORTC_ID,PIN6_ID,PORTC_PIN6_DIRECTION,PORTC_PIN6_DATA,PORTC_PIN6_MODE_TYPE,PORTC_PIN6_RESISTOR,PORTC_PIN6_DIRECTION_CHANGABLE,PORTC_PIN6_MODE_CHANGABLE, /* PIN6 */
		PORTC_ID,PIN7_ID,PORTC_PIN7_DIRECTION,PORTC_PIN7_DATA,PORTC_PIN7_MODE_TYPE,PORTC_PIN7_RESISTOR,PORTC_PIN7_DIRECTION_CHANGABLE,PORTC_PIN7_MODE_CHANGABLE, /* PIN7 */
                /*****************************************************************   PORT D  *************************************************************************/
		PORTD_ID,PIN0_ID,PORTD_PIN0_DIRECTION,PORTD_PIN0_DATA,PORTD_PIN0_MODE_TYPE,PORTD_PIN0_RESISTOR,PORTD_PIN0_DIRECTION_CHANGABLE,PORTD_PIN0_MODE_CHANGABLE, /* PIN0 */
		PORTD_ID,PIN1_ID,PORTD_PIN1_DIRECTION,PORTD_PIN1_DATA,PORTD_PIN1_MODE_TYPE,PORTD_PIN1_RESISTOR,PORTD_PIN1_DIRECTION_CHANGABLE,PORTD_PIN1_MODE_CHANGABLE, /* PIN1 */
		PORTD_ID,PIN2_ID,PORTD_PIN2_DIRECTION,PORTD_PIN2_DATA,PORTD_PIN2_MODE_TYPE,PORTD_PIN2_RESISTOR,PORTD_PIN2_DIRECTION_CHANGABLE,PORTD_PIN2_MODE_CHANGABLE, /* PIN2 */
		PORTD_ID,PIN3_ID,PORTD_PIN3_DIRECTION,PORTD_PIN3_DATA,PORTD_PIN3_MODE_TYPE,PORTD_PIN3_RESISTOR,PORTD_PIN3_DIRECTION_CHANGABLE,PORTD_PIN3_MODE_CHANGABLE, /* PIN3 */
		PORTD_ID,PIN4_ID,PORTD_PIN4_DIRECTION,PORTD_PIN4_DATA,PORTD_PIN4_MODE_TYPE,PORTD_PIN4_RESISTOR,PORTD_PIN4_DIRECTION_CHANGABLE,PORTD_PIN4_MODE_CHANGABLE, /* PIN4 */
		PORTD_ID,PIN5_ID,PORTD_PIN5_DIRECTION,PORTD_PIN5_DATA,PORTD_PIN5_MODE_TYPE,PORTD_PIN5_RESISTOR,PORTD_PIN5_DIRECTION_CHANGABLE,PORTD_PIN5_MODE_CHANGABLE, /* PIN5 */
		PORTD_ID,PIN6_ID,PORTD_PIN6_DIRECTION,PORTD_PIN6_DATA,PORTD_PIN6_MODE_TYPE,PORTD_PIN6_RESISTOR,PORTD_PIN6_DIRECTION_CHANGABLE,PORTD_PIN6_MODE_CHANGABLE, /* PIN6 */
		PORTD_ID,PIN7_ID,PORTD_PIN7_DIRECTION,PORTD_PIN7_DATA,PORTD_PIN7_MODE_TYPE,PORTD_PIN7_RESISTOR,PORTD_PIN7_DIRECTION_CHANGABLE,PORTD_PIN7_MODE_CHANGABLE, /* PIN7 */
                /*****************************************************************   PORT E  *************************************************************************/
		PORTE_ID,PIN0_ID,PORTE_PIN0_DIRECTION,PORTE_PIN0_DATA,PORTE_PIN0_MODE_TYPE,PORTE_PIN0_RESISTOR,PORTE_PIN0_DIRECTION_CHANGABLE,PORTE_PIN0_MODE_CHANGABLE, /* PIN0 */
		PORTE_ID,PIN1_ID,PORTE_PIN1_DIRECTION,PORTE_PIN1_DATA,PORTE_PIN1_MODE_TYPE,PORTE_PIN1_RESISTOR,PORTE_PIN1_DIRECTION_CHANGABLE,PORTE_PIN1_MODE_CHANGABLE, /* PIN1 */
		PORTE_ID,PIN2_ID,PORTE_PIN2_DIRECTION,PORTE_PIN2_DATA,PORTE_PIN2_MODE_TYPE,PORTE_PIN2_RESISTOR,PORTE_PIN2_DIRECTION_CHANGABLE,PORTE_PIN2_MODE_CHANGABLE, /* PIN2 */
		PORTE_ID,PIN3_ID,PORTE_PIN3_DIRECTION,PORTE_PIN3_DATA,PORTE_PIN3_MODE_TYPE,PORTE_PIN3_RESISTOR,PORTE_PIN3_DIRECTION_CHANGABLE,PORTE_PIN3_MODE_CHANGABLE, /* PIN3 */
		PORTE_ID,PIN4_ID,PORTE_PIN4_DIRECTION,PORTE_PIN4_DATA,PORTE_PIN4_MODE_TYPE,PORTE_PIN4_RESISTOR,PORTE_PIN4_DIRECTION_CHANGABLE,PORTE_PIN4_MODE_CHANGABLE, /* PIN4 */
		PORTE_ID,PIN5_ID,PORTE_PIN5_DIRECTION,PORTE_PIN5_DATA,PORTE_PIN5_MODE_TYPE,PORTE_PIN5_RESISTOR,PORTE_PIN5_DIRECTION_CHANGABLE,PORTE_PIN5_MODE_CHANGABLE, /* PIN5 */
                /*****************************************************************   PORT F  *************************************************************************/
		PORTF_ID,PIN0_ID,PORTF_PIN0_DIRECTION,PORTF_PIN0_DATA,PORTF_PIN0_MODE_TYPE,PORTF_PIN0_RESISTOR,PORTF_PIN0_DIRECTION_CHANGABLE,PORTF_PIN0_MODE_CHANGABLE, /* PIN0 */
		PORTF_ID,PIN1_ID,PORTF_PIN1_DIRECTION,PORTF_PIN1_DATA,PORTF_PIN1_MODE_TYPE,PORTF_PIN1_RESISTOR,PORTF_PIN1_DIRECTION_CHANGABLE,PORTF_PIN1_MODE_CHANGABLE, /* PIN1 */
		PORTF_ID,PIN2_ID,PORTF_PIN2_DIRECTION,PORTF_PIN2_DATA,PORTF_PIN2_MODE_TYPE,PORTF_PIN2_RESISTOR,PORTF_PIN2_DIRECTION_CHANGABLE,PORTF_PIN2_MODE_CHANGABLE, /* PIN2 */
		PORTF_ID,PIN3_ID,PORTF_PIN3_DIRECTION,PORTF_PIN3_DATA,PORTF_PIN3_MODE_TYPE,PORTF_PIN3_RESISTOR,PORTF_PIN3_DIRECTION_CHANGABLE,PORTF_PIN3_MODE_CHANGABLE, /* PIN3 */
		PORTF_ID,PIN4_ID,PORTF_PIN4_DIRECTION,PORTF_PIN4_DATA,PORTF_PIN4_MODE_TYPE,PORTF_PIN4_RESISTOR,PORTF_PIN4_DIRECTION_CHANGABLE,PORTF_PIN4_MODE_CHANGABLE, /* PIN4 */
};

